alias v="nvim"
alias p="sudo pacman"
alias sv="sudo nvim"
alias vc="nvim ~/.zshrc"
alias vvc="nvim ~/.config/nvim/init.lua"
alias ff="fastfetch --logo Trisquel"
alias src="source ~/.zshrc"
alias vkitty="nvim ~/.config/kitty/kitty.conf"
alias vi3="nvim ~/.config/i3/config"
alias fq="fc-query -f '%{family[0]}\n'"
alias khali="khal interactive"
alias ytd="yt-dlp"
alias ac="aria2c"
alias zo="zoxide"
alias za="zathura"
alias tmw="timew"
alias tw="task"

