-- c_lsp.lua — C autocompletion via clangd + nvim-cmp
-- Generated by setup_c_lsp.sh
-- Add to your lazy.nvim plugin spec and require this file in init.lua:
--   require("c_lsp")

-- ── Mason ────────────────────────────────────────────────────────────────────
require("mason").setup()

require("mason-lspconfig").setup({
  ensure_installed = { "clangd" },
  automatic_installation = true,
})

-- ── clangd via lspconfig ──────────────────────────────────────────────────────
local capabilities = require("cmp_nvim_lsp").default_capabilities()

require("lspconfig").clangd.setup({
  capabilities = capabilities,
  cmd = { "clangd", "--background-index", "--clang-tidy" },
  on_attach = function(_, bufnr)
    local opts = { buffer = bufnr, silent = true }
    vim.keymap.set("n", "gd",  vim.lsp.buf.definition,      opts)  -- go to definition
    vim.keymap.set("n", "K",   vim.lsp.buf.hover,            opts)  -- docs on hover
    vim.keymap.set("n", "gr",  vim.lsp.buf.references,       opts)  -- find references
    vim.keymap.set("n", "<leader>rn", vim.lsp.buf.rename,    opts)  -- rename symbol
    vim.keymap.set("n", "<leader>ca", vim.lsp.buf.code_action, opts) -- code actions
  end,
})

-- ── nvim-cmp ─────────────────────────────────────────────────────────────────
local cmp     = require("cmp")
local luasnip = require("luasnip")

cmp.setup({
  snippet = {
    expand = function(args)
      luasnip.lsp_expand(args.body)
    end,
  },
  mapping = cmp.mapping.preset.insert({
    ["<C-Space>"] = cmp.mapping.complete(),           -- trigger manually
    ["<C-e>"]     = cmp.mapping.abort(),              -- close menu
    ["<CR>"]      = cmp.mapping.confirm({ select = true }),
    ["<Tab>"] = cmp.mapping(function(fallback)
      if cmp.visible() then
        cmp.select_next_item()
      elseif luasnip.expand_or_jumpable() then
        luasnip.expand_or_jump()
      else
        fallback()
      end
    end, { "i", "s" }),
    ["<S-Tab>"] = cmp.mapping(function(fallback)
      if cmp.visible() then
        cmp.select_prev_item()
      elseif luasnip.jumpable(-1) then
        luasnip.jump(-1)
      else
        fallback()
      end
    end, { "i", "s" }),
  }),
  sources = cmp.config.sources({
    { name = "nvim_lsp" },
    { name = "luasnip" },
  }),
  window = {
    completion    = cmp.config.window.bordered(),
    documentation = cmp.config.window.bordered(),
  },
})
